### ISSUE TITLE
Leave setting values as `Undefined` rather than coercing to `nil` for un-set settings

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-configurable#108]
This is something @solnic mentioned a while ago as a change he'd like to see for 1.0.0. Opening this so we can have the discussion as whether this is something we still want.

**Comment by timriley** [comment]
Related to this would be changing the expected signature for setting value processor blocks: they must be prepared for their value argument _not_ to be provided for undefined values, so a processor block like this:

```ruby
-> v {
  # some logic
}
```

Must become:

```ruby
-> v = "default" {
  # some logic
}
```

**Comment by flash-gordon** [comment]
I'm in favor. This is definitely the place that can benefit from `Undefined`. I wish we didn't have to break things but this is for the greater good :) Mb we could have prev behavior ... configurable (but not default).
