### ISSUE TITLE
Understanding the thread safety claim - random sum every program invocation

### ISSUE THREAD

**Issue by feliperaul** [dry-rb/dry-configurable#118]
## Describe the bug

I'd like to understand a little bit more about the thread-safety claim, since a test program I wrote (inspired from https://www.yegor256.com/2018/11/06/ruby-threads.html) is returning a random sum on every program invocation, while without threads the result is stable.

Given this code:

```rb
class Program
  extend Dry::Configurable

  setting :counter

  def self.call; new.call; end

  def call
    self.class.config.counter = 1
    2.times.map do
      Thread.new do
        50.times do
          number_value = self.class.config.counter
          sleep(0.001)
          self.class.config.counter = self.class.config.counter + number_value
        end
      end
    end.each(&:join)
    self.class.config.counter
  end
end
```

## To Reproduce

`Program.call`

Return value should be `1267650600228229401496703205376`, which is what you get when you comment the `Thread.new do` and `end.each(&:join)` lines above, so no Threads are involved.

## Expected behavior

Return is random:

```rb
Program.call
=> 927372692193078999176
Program.call
=> 1052337743009943038933
Program.call
=> 927372692193078999176
Program.call
=> 1052338402766319185501
Program.call
=> 1116795285174159114038
```

## My environment

- Affects my production application: NO
- Ruby version: 2.7.2
- OS: Mac OS X 10.15

**Comment by flash-gordon** [comment]
Please forward questions to out forward, github is for bug tracking or feature requests previously discussed on the forum. In a nutshell, your code lacks synchronization, dry-configurable cannot do it for you.
