### ISSUE TITLE
0.13.0 release checklist

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-configurable#120]
The upcoming 0.13.0 release will include a couple of large changes:

1. Deprecating setting constructors provided via a block, favouring the `constructor:` argument instead
2. Requiring default values be provided as a `default:` argument, rather than a second positional argument

While we've strived for these changes to be backwards compatible, they may cause breakage in certain circumstances.

To this end, we need to make sure we coordinate this 0.13.0 release of dry-configurable with all the gems that use it within the dry-rb, rom-rb, and Hanami ecosystems. This issue will serve as this coordination point.

## Testing dependent gems

To make sure the new dry-configurable 0.13.0 release offers the appropriate level of backwards compatibility, we want to test all of its dependent gems across the dry-rb/rom-rb/hanami ecosystem.

The table below tracks the test we're (manually) running on each gem. The tests should exercise each of these cases:

- The latest release of the gem, using dry-configurable 0.12.1, on Ruby 3.0
- The latest release of the gem, using dry-configurable 0.12.1, on Ruby 2.7
- The latest release of the gem, using dry-configurable 0.13.0 (master), on Ruby 3.0
- The latest release of the gem, using dry-configurable 0.13.0 (master), on Ruby 2.7
- The branch of the gem with dry-configurable 0.13.0 updates, using dry-configurable 0.13.0 (master), on Ruby 3.0
- The branch of the gem with dry-configurable 0.13.0 updates, using dry-configurable 0.13.0 (master), on Ruby 2.7

The tests should pass in all cases.

Testing instructions are as follows:

1. In your working copy, run `git fetch --all --tags` to get all tags
2. Check out the the branch or tag for the test, e.g. `git checkout tags/v0.8.0` or `git checkout master`
3. Ensure the gemspec points to the appropriate version of dry-configurable for the test, e.g. `0.12.1` or the `master` branch
4. Run the test suite and ensure it passes

| Dependent gem | dry-configurable 0.12.1 | dry-configurable 0.13.0 |
| -- | -- | -- |
| dry-container @ v0.8.0 @ ruby 3.0 | ✅ | ✅ |
| dry-container @ v0.8.0 @ ruby 2.7 | ✅ | ✅ |
| dry-container @ master @ ruby 3.0 | n/a | ✅ |
| dry-container @ master @ ruby 2.7 | n/a | ✅ |
| dry-effects @ v0.1.5 @ ruby 3.0 | ✅ ([see note](#dry-effects-1)) | ✅ |
| dry-effects @ v0.1.5 @ ruby 2.7 | ✅ | ✅ |
| dry-effects @ master @ ruby 3.0 | n/a | ✅ |
| dry-effects @ master @ ruby 2.7 | n/a | ✅ |
| dry-monitor @ v0.4.0 @ ruby 3.0 | ✅ | ✅ |
| dry-monitor @ v0.4.0 @ ruby 2.7 | ✅ | ✅ |
| dry-monitor @ https://github.com/dry-rb/dry-monitor/pull/43 @ ruby 3.0 | n/a | ✅ |
| dry-monitor @ https://github.com/dry-rb/dry-monitor/pull/43 @ ruby 2.7 | n/a | ✅ |
| dry-rails @ v.0.3.0 @ ruby 3.0 | ✅ ([see note](#dry-rails-1))| ✅ (with dry-system `release-0.18` branch) |
| dry-rails @ v.0.3.0 @ ruby 2.7 | ✅ | ✅ (with dry-system `release-0.18` branch) |
| dry-rails @ https://github.com/dry-rb/dry-rails/pull/44 @ ruby 3.0 | n/a | ✅ (with dry-system `release-0.18` branch) |
| dry-rails @ https://github.com/dry-rb/dry-rails/pull/44 @ ruby 2.7 | n/a | ✅ (with dry-system `release-0.18` branch) |
| ~dry-schema @ v.1.7.0 @ ruby 3.0~ | ✅ | n/a (see rows below, and [original failure note](#dry-schema-1)) |
| ~dry-schema @ v.1.7.0 @ ruby 2.7~ | n/a | n/a |
| dry-schema @ v.1.7.1 @ ruby 3.0 | ✅ | ✅ |
| dry-schema @ v.1.7.1 @ ruby 2.7 | ✅ | ✅ |
| dry-schema @ https://github.com/dry-rb/dry-schema/pull/356 @ ruby 3.0 | n/a | |
| dry-schema @ https://github.com/dry-rb/dry-schema/pull/356 @ ruby 2.7 | n/a | |
| ~dry-system @ 0.19.1 @ ruby 3.0~ | ✅ | n/a (see rows below, and [original failure note](#dry-system-1)) |
| ~dry-system @ 0.19.1 @ ruby 2.7~ | n/a (see rows below) | n/a |
| dry-system @ https://github.com/dry-rb/dry-system/pull/186 (fix for 0.19.1) @ ruby 3.0 | ✅ | ✅ |
| dry-system @ https://github.com/dry-rb/dry-system/pull/186 (fix for 0.19.1) @ ruby 2.7 | ✅ | ✅ |
| dry-system @ master @ ruby 3.0 | n/a | ✅ |
| dry-system @ master @ ruby 2.7 | n/a | ✅ |
| dry-validation @ v1.6.0 @ ruby 3.0 | ✅ ([see note](#dry-validation-1)) | ✅ |
| dry-validation @ v1.6.0 @ ruby 2.7 | ✅ | ✅ |
| dry-validation @ https://github.com/dry-rb/dry-validation/pull/686 @ ruby 3.0 | n/a | ✅ |
| dry-validation @ https://github.com/dry-rb/dry-validation/pull/686 @ ruby 2.7 | n/a | ✅ |
| hanami-view @ v2.0.0.alpha2 @ ruby 3.0 | ✅ | ✅ (with dry-system `release-0.19` branch) |
| hanami-view @ v2.0.0.alpha2 @ ruby 2.7 | ✅ | ✅ (with dry-system `release-0.19` branch) |
| hanami-view @ master @ ruby 3.0 | n/a | ✅ |
| hanami-view @ master @ ruby 2.7 | n/a | ✅ |
| hanami @ v2.0.0.alpha2 @ ruby 3.0 | ✅ | ✅ (with dry-system `release-0.19` branch) |
| hanami @ v2.0.0.alpha2 @ ruby 2.7 | ✅ | ✅ (with dry-system `release-0.19` branch) |
| hanami @ main @ ruby 3.0 | n/a | ✅ |
| hanami @ main @ ruby 2.7 | n/a | ✅ |

#### dry-effects @ v0.1.5 @ ruby 3.0
<div id="dry-effects-1"></div>

This has some unrelated failures at the moment due to breaking changes in dry-system (e.g. moving of the default_namespace setting). I temporarily fixed these by pinning to an older dry-system just for the tests.

#### dry-rails @ v.0.3.0 @ ruby 3.0
<div id="dry-rails-1"></div>

Specs here are failing because ActiveSupport's core extensions are not loaded and `spec/dummy-6.x/dummy/config/environments/test.rb` uses `1.hour`, which results in this error:

```
An error occurred while loading spec_helper.
Failure/Error: "Cache-Control" => "public, max-age=#{1.hour.to_i}"

NoMethodError:
  undefined method `hour' for 1:Integer
# ./spec/dummy-6.x/dummy/config/environments/test.rb:21:in `block in <top (required)>'
# ./spec/dummy-6.x/dummy/config/environments/test.rb:8:in `<top (required)>'
# ./spec/dummy-6.x/dummy/config/environment.rb:7:in `<top (required)>'
# ./spec/spec_helper.rb:19:in `require'
# ./spec/spec_helper.rb:19:in `<top (required)>'
```

A quick fix is to chuck `require "active_support/all"` in `spec_helper.rb`, just above the require to the dummy app's `config/environment`.

This should be properly fixed in a separate PR.

<h4 id="dry-schema-1">dry-schema @ v.1.7.0 @ ruby 3.0 + dry-configurable 0.13.0</h4>

8 failing tests, all with the same error:

```
no implicit conversion of Dry::Configurable::Config into Hash
```

This is because I removed that implicit hash conversion in https://github.com/dry-rb/dry-configurable/pull/114.

We'll need to update dry-schema to do explicit hash conversion and release that first.

<h4 id="dry-system-1">dry-system @ 0.19.1 + dry-configurable 0.13.0</h1>

Now fixed in https://github.com/dry-rb/dry-system/pull/186.

<details><summary>Original failure details:</summary>
<p>

This fails with the following error:

```
     Failure/Error: super(name, *args, &block)

     ArgumentError:
       wrong number of arguments (given 3, expected 1..2)
     # ./lib/dry/system/container.rb:105:in `setting'
```

The problem is with the params signature of the `Dry::System::Container.setting` override method, which I'm not entirely sure is even needed anymore. This will need a fix and a release to do more flexible argument forwarding before other gems depending on dry-system (i.e. hanami and dry-rails) can be compatible with the upcoming dry-configurable release.

A fix for this is already included in https://github.com/dry-rb/dry-system/pull/179, which is merged into master, but alongside changes to use the latest dry-configurable `setting` API.

⚠️ We'll need to isolate a fix to the `Dry::System::Container.setting` override method (ideally something that has more flexible argument forwarding so that it works with both versions of dry-configurable) and release that as an independent patch release, separate from any of the other changes currently in dry-system master.
</p>
</details>

<h4 id="dry-validation-1">dry-validation @ v.1.6.0 @ ruby 3.0 + dry-configurable 0.12.1</h4>

The tests all pass apart from this flaky spec [that has seen been disabled](https://github.com/dry-rb/dry-validation/commit/1137acec35c08758145e2a7d2d8e95ae32f0a84d).

## Updating dependent gems to use the new API

Here's a list of PRs to dependent gems to have them use the API.

n.b. the dry-validation and dry-schema PRs had some attempts at special compatibility shim code that should no longer needed now that dry-configurable 0.13.0 offers better backwards compatibility. These shims should be removed before testing.

- https://github.com/hanami/view/pull/190
- https://github.com/dry-rb/dry-system/pull/179
- https://github.com/dry-rb/dry-container/pull/77
- https://github.com/dry-rb/dry-effects/pull/83
- https://github.com/dry-rb/dry-monitor/pull/43
- https://github.com/dry-rb/dry-schema/pull/356
- https://github.com/dry-rb/dry-validation/pull/686
- https://github.com/dry-rb/dry-rails/pull/44

Once these are all merged (and all the tests in the previous section are completed), we can consider a release.

## Releasing the gems

_This section still needs more work, but it'll be something like this_

1. Release dry-configurable 0.13.0
2. For each of the gems above, make sure the PR to add the dry-configurable API changes is merged
3. Bump their minimum dry-configurable version requirement to 0.13.0
4. Cut a new minor release, e.g. `x.[THIS ONE].y` (?? - I think minor is better than patch because that way we're less likely to foist a whole bunch of deprecation notices on our users unsuspectingly)

**Comment by timriley** [comment]
@solnic Regarding [the comment you left here](https://github.com/dry-rb/dry-schema/pull/356#pullrequestreview-667486323):

> The same case as with dry-validation - I think it'd be good to make it work with both versions of dry-configurable.

Given that the approach you tried for dry-validation won't work for dry-schema given it makes use of nested settings (and we can't make a local patch for the `setting` method inside that nested evaluation context, should we reconsider our approach?

Given that the changes for the next dry-configurable release are broadly backwards compatible (I think there might be just one issue with hashes provided as defaults, which I can dig into more if we decide to go down this path), and with deprecation warnings being printed for the previous style of supplied arguments to `setting`, could we contemplate just releasing the new dry-configurable, and then bumping the required minimum dry-configurable version across new releases of all the other gems that depend on it?

**Comment by timriley** [comment]
Here's a single test encompassing the bug with our (supposedly) backwards-compatible-but-deprecated support for default values provided as the second positional argument to `setting`: https://github.com/dry-rb/dry-configurable/pull/121

It works with Ruby 3.0 but fails in 2.6 and 2.7. If we can find a way to sort that out, the I think I'd be confident to go ahead with the release and versioning approach I've described above.

**Comment by timriley** [comment]
#121 is now a full-blown fix and, once that is reviewed and merged, I think we can be confident about the following as the release process:

1. Do another round of testing of the `main`/`master` branch of each of the dependent gems on both (a) the current version and (b) the `master` branch of dry-configurable. If they work without any changes required
2. Do another round of testing of the "upgrade dry-configurable" PRs (linked in the top description) and make sure they all work on the `master` branch of of dry-configurable
2. Release dry-configurable 0.13.0
3. Release all the dependent gems with new `>= 0.13.0` version constraints against dry-configurable and using the new `setting` API

And once we do the latter, even if users pull the latest dry-configurable as a transitive dependency, it shouldn’t break any of their apps because we’ve now covered all the backwards compatibility cases. Worst thing will be that they see a bunch of deprecation warnings and will need to upgrade their setting definitions to silence them (and we can make sure the dry-configurable CHANGELOG makes it really clear what they need to do).

**Comment by timriley** [comment]
@solnic @flash-gordon — let me know if you're good with the above?

**Comment by timriley** [comment]
@solnic Is there any rom stuff I need to be testing at this point, or since dry-configurable is being newly introduced there, we don't need to worry about any compatibility issues?

**Comment by waiting-for-dev** [comment]
@timriley, to complete the process, once dry-configurable v0.13 has been released we should add it into the `gemspec` file in `hanami/hanami`, as it's now on its `Gemfile`:

https://github.com/hanami/hanami/blob/b449ef1ebaaf3e1056f5c1e882ddb326586c2811/Gemfile#L20

**Comment by timriley** [comment]
Hi @VikiAnn — we shipped the following dry-rb gem releases to use the latest dry-configurable 0.13.0 API:

- dry-container 0.9.0
- dry-system 0.19.2
- dry-system 0.20.0
- dry-monitor 0.5.0
- dry-schema 1.8.0
- dry-validation 1.7.0

If you upgrade to those versions, you should see any deprecation warnings originating from dry-rb gems going away.

As for warnings from other gems, you may need to work with their maintainers to get them in place.

If you need to temporarily silence these warnings while you wait for upstream adjustments, you might also find the https://github.com/jeremyevans/ruby-warning gem handy.

Thanks!
