### ISSUE TITLE
to_h method for config

### ISSUE THREAD

**Issue by krisleech** [dry-rb/dry-configurable#13]
Would you be open to a PR to add a `to_h` method to [config](https://github.com/dry-rb/dry-configurable/blob/master/lib/dry/configurable/config.rb#L20) allowing:

```ruby
App.configure do |config|
  config.database.dsn = 'jdbc:sqlite:memory'
end

App.config.to_h # => { dsn: 'jdbc:sqlite:memory' }
```

This would allow me to output all the configuration to the display without having to know all the keys.

By the way I could swear this used to be possible in an earlier version :)

EDIT: I think an earlier version might have used `Struct` which provided the `to_h` method.

**Comment by AMHOL** [comment]
@krisleech yeah sorry I have just yanked 0.2.0, see https://github.com/dry-rb/dry-configurable/issues/12

**Comment by AMHOL** [comment]
@krisleech also, yeah would appreciate a PR :)

**Comment by AMHOL** [comment]
See https://github.com/dry-rb/dry-configurable/pull/15

**Comment by krisleech** [comment]
quick as lightening :zap:
