### ISSUE TITLE
`v0.16.0` of dry-configurable breaks `require "dry-validation"`

### ISSUE THREAD

**Issue by marian13** [dry-rb/dry-configurable#146]
## Describe the bug

`v0.16.0` release affects `"dry-validation"`.

Please, check this GitHub Actions [run](https://github.com/marian13/convenient_service/actions/runs/3214347635/jobs/5254708991):

<img width="1372" alt="Screenshot 2022-10-09 at 17 39 58" src="https://user-images.githubusercontent.com/22632866/194762966-9b15fdcb-af2a-43d1-babd-7580f0fa019e.png">

## To Reproduce

Open `irb` for Ruby 3.1.

```bash
irb
```

Try to require `"dry-validation"`.

```ruby
require "dry-validation"
```

Check the following screenshot to see what happens:

<img width="720" alt="Screenshot 2022-10-09 at 17 13 27" src="https://user-images.githubusercontent.com/22632866/194761649-4ff1bb54-eaf7-45d5-88ab-d31562fec65d.png">

`"dry-validation"` version - `v1.5.6`.

<img width="720" alt="Screenshot 2022-10-09 at 17 28 58" src="https://user-images.githubusercontent.com/22632866/194762416-a38d9b77-f27e-412b-b6dc-9b794f46af37.png">

`"dry-schema"` version - `v1.10.6`.

<img width="720" alt="Screenshot 2022-10-09 at 17 29 19" src="https://user-images.githubusercontent.com/22632866/194762470-1c525c48-9452-48ef-abf7-5fd6549a6e2c.png">

`"dry-configurable"` version - `v0.16.0`.

<img width="720" alt="Screenshot 2022-10-09 at 17 29 36" src="https://user-images.githubusercontent.com/22632866/194762471-5b0f8337-a28d-427b-9530-0b3ddf1b295e.png">

## Expected behavior

As it was in `v0.15.0`. A successful `require`.
 
## My environment

- Affects my production application: **NO**, but I am planning to release `v0.1.0` of [convenient_service](https://github.com/marian13/convenient_service/tree/d3c76dc847a428bb17199a8d90302941f0ae7dad) (that may depend on dry-validation) at the beginning of November.
- Ruby version: 3.1.
- OS: Linux (GitHub Actions [config](https://github.com/marian13/convenient_service/blob/d3c76dc847a428bb17199a8d90302941f0ae7dad/.github/workflows/ci.yml), Docker [config](https://github.com/marian13/convenient_service/blob/d3c76dc847a428bb17199a8d90302941f0ae7dad/docker/3.1/Dockerfile)).

**Comment by solnic** [comment]
This has been addressed already, could you upgrade to the latest version (1.8.1)? I'm gonna close this as there's nothing to do.

**Comment by marian13** [comment]
Thank you.
