### ISSUE TITLE
Changelog for v1.0.2 not in main branch

### ISSUE THREAD

**Issue by ssoulless** [dry-rb/dry-configurable#162]
Just want to ask if there's any reason why the changelog for v1.0.2 is not in the main branch, our dependabot recently tried to upgrade this gem to v1.0.2 however I was not able to find the changelog for this version, looking at the git tags I could find the 1.0.2 tag and its changelog here https://github.com/dry-rb/dry-configurable/blob/v1.0.2/CHANGELOG.md#102-2022-07-16

just wondering if there's any reason why this version is missing from the main changelog.

**Comment by timriley** [comment]
No reason at all - if you could make the main branch changelog complete via a PR, I'd be very happy to merge it! Thanks!

**Comment by ssoulless** [comment]
Well after taking a closer look it seems that the patch version 1.0.2 vas just renamed to the minor version 1.1.0, so that's why there's no changelog for v1.0.2 because now it just became 1.1.0
