### ISSUE TITLE
Reset configuration

### ISSUE THREAD

**Issue by waiting-for-dev** [dry-rb/dry-configurable#19]
I'm developing a gem that uses dry-configurable. In order to test it, I need to change some default settings in `before` hooks. I found that changed settings persist in subsequent tests. For that reason, I think I would need some `reset` method in order to apply it in `after` hooks.

What do you think about it? Would it be difficult to implement or does it have any drawback?

**Comment by mereghost** [comment]
@waiting-for-dev A very hackish way to do that currently, is by removing `@_config` like this

```ruby
class App
  extend Dry::Configurable

  setting :important, 'default'

 def self.reset
  remove_instance_variable :@_config
 end
end
```

**Comment by solnic** [comment]
We can add it as a test-specific interface that people could include on demand
