### ISSUE TITLE
Reader pre-processor

### ISSUE THREAD

**Issue by waiting-for-dev** [dry-rb/dry-configurable#25]
We already have a writer pre-processor:

```ruby
setting(:file) { |value| Pathname(value) }
```

But now, I'm in a use case where a reader pre-processor could also be useful.  In my case I would like to throw an error if an important setting is not set. I think it would be nice to do it in the configuration layer, because it is its outermost boundary.

I see that having a setting with both writer and reader pre-processors could look a bit clumsy:

```ruby
setting(:file,
        reader: ->(value) { value || raise('+file+ setting must be defined') }
       ) { |value| Pathname(value) }
```

If we are not in a "don't break backwards compatibility" phase, we could instead do:

```ruby
setting(:file,
        reader: ->(value) { value || raise('+file+ setting must be defined') },
        writer: ->(value) { Pathname(value) })
```

Or, in order not to break compatibility, we could make a single block default to a writer pre-processor.

What do you think about it?

**Comment by AMHOL** [comment]
@waiting-for-dev I like this idea, going to add 1.0 milestone and then we can break what we like lol

FWIW for 1.0 I also plan to address #8 and change the default value to a keyword argument (`default`)

**Comment by waiting-for-dev** [comment]
Sounds good ;)

So, do you also think having both `reader` & `writer` options would be the best syntax? I think it is the most explicit and clear.

**Comment by AMHOL** [comment]
Yeah I think so too, then it could just default to identity function

**Comment by GustavoCaso** [comment]
@waiting-for-dev are you currently working on it? If not I would like to have a look see if I can implement it.

**Comment by waiting-for-dev** [comment]
@GustavoCaso feel free to take it

**Comment by GustavoCaso** [comment]
Awesome @waiting-for-dev

**Comment by AMHOL** [comment]
BTW I think that we should use `:setter` and `:getter` rather than `:reader` and `:writer` so that we can leave `:reader` and `:writer` open for #8.

**Comment by waiting-for-dev** [comment]
Hmm... I don't like `setter` and `getter` nomenclature... it's not that important, but I think is not idiomatic in Ruby. More importantly, it would be quite confusing to remember which pair does what...

If #8 is going to be implemented (I'm not sure it is a good idea), maybe we could call that pair `forward_reader` and `forward_writter` ?

**Comment by AMHOL** [comment]
Perhaps we could just go with something like:

```ruby
setting :path,
        default: Dir.pwd,
        reader: ->(value) { value || raise('+file+ setting must be defined') },
        writer: ->(value) { Pathname(value) },
        accessor: true|symbol|string
```

**Comment by solnic** [comment]
I'd rather have support for dry-types than adding many options, ie:

``` ruby
Path = Types::Definition.new(Pathname).constructor(Kernel.method(:Pathname).default(Dir.pwd)

setting :path, Types::Path, reader: true # like proposed in issue #8
```

And I'm more than happy to add new methods to dry-types to make defining similar types more concise (which was the plan anyway).

WDYT?

**Comment by AMHOL** [comment]
@solnic I really like this, I think we need to make it the direction for 1.0

**Comment by GustavoCaso** [comment]
@solnic That looks awesome

**Comment by waiting-for-dev** [comment]
It looks nice to integrate dry-types with dry-configuragion settings. It seems a perfect fit. However I have some concerns:

* 

> ```ruby
> Path = Types::Definition.
> new(Pathname).
>  constructor(Kernel.method(:Pathname).
>  default(Dir.pwd)
>
> setting :path, Types::Path, reader: true
> ```

  Don't you think is it overkilling having to write all of this to define a default value? Or maybe I'm a bit confused and you are talking more at an internal implementation level?

* I'm not too familiar with dry-types. Would this allow to pre-process values on both read / write phases?

Having said that, I'm also a bit concerned the API would become a bit bloated adding so many named options, so I like this clear separation.

**Comment by solnic** [comment]
> Don't you think is it overkilling having to write all of this to define a default value?

As I mentioned we can have simplified APIs in dry-types to make it very concise. I showed how it can be done already, which includes coercion using Pathname and a default value. You can also add a constraint that will check that the value is set. All these problems are solved in dry-types and its one of the ways of using this library. Coercions, constraints, default values, it's all there. Not to mention that types are small, reusable objects, and can be shared across multiple places in a system.

> Or maybe I'm a bit confused and you are talking more at an internal implementation level?

Nope, I'm talking about using a type object to process a setting value. We just need a simpler API in dry-types for defining common things like this `Path` example.

> I'm not too familiar with dry-types. Would this allow to pre-process values on both read / write phases?

Why would you want to pre-process when reading a value? A setting value should be processed once and stored. No need to pre-process many times.

**Comment by waiting-for-dev** [comment]
> As I mentioned we can have simplified APIs in dry-types to make it very concise.

Ok, then I like the idea. I just was concerned it was going to be cumbersome to use. If not, then I think dry-types is the perfect solution :)

> Why would you want to pre-process when reading a value? A setting value should be processed once and stored. No need to pre-process many times.

Well, the main scenario I had in mind was raising an error on reading if the setting was not set, but you already mentioned that constraints could be checked by dry-types.

Another scenario would be a value that depends on current time. For example and OTP drift being 30 seconds from the time the value is accessed. I wonder if it could be nice to get the actual expiration time from dry-configuration or simply it would be better to wrap it in another method.

Also, one could have a setting which references the information to open a connection to some server. This is heavy, so maybe it could be nice to open it only if it is used at the reading time.

**Comment by solnic** [comment]
> Another scenario would be a value that depends on current time. For example and OTP drift being 30 seconds from the time the value is accessed. I wonder if it could be nice to get the actual expiration time from dry-configuration or simply it would be better to wrap it in another method.

You can define a type with default using a proc and it will do exactly what you need (via dry-types), so no need to add special features to dry-configurable :)

**Comment by waiting-for-dev** [comment]
Cool! :smile:

**Comment by solnic** [comment]
I should mention that we called this organization "dry" not just because it's short and sweet but because we'd like to...sort of remind people that dry is more about abstractions than about repeating the same word twice, that's why there's *big* focus on building good abstractions that are shared across the gems, while at the same time avoiding JS-like micro lib bloat. This is why I suggested using dry-types because it literally gives us everything we need for the functionality we'd like to have in dry-configurable.

**Comment by waiting-for-dev** [comment]
Yep, it makes all the sense :+1:

**Comment by GustavoCaso** [comment]
It makes total sense. One question maybe is out of context, but after adding the `Dry::Types` compatibility into the gem, the user could still use it without the `Dry::Types` ?

**Comment by solnic** [comment]
@GustavoCaso yes this should optional

**Comment by saverio-kantox** [comment]
>  I showed how it can be done already, which includes coercion using Pathname and a default value.

@solnic Maybe I have misunderstood, but when I try to use this (seemingly already supported) form, it does not seem to work as intended.

```ruby
# Authorizer. It will be called with a user instance.
Authorizer = ::Dry::Types::Definition.new(Proc)
  .constructor(proc do |value = nil|
    case value
    when Proc then value
    when Symbol, Method then value.to_proc
    when nil, false then proc { |_any| true }
    else raise "not supported"
    end
  end)
  .default(-> { proc { |_any| true } })

class Superclass
  setting :authorizer, Authorizer
end

class Subclass < Superclass
  config.authorizer = :admin?
end

# but what happens is:

Superclass.config.authorizer
# => the actual type, not the default value
Subclass.config.authorizer
# => just the symbol, the type constructor is not being called.
```

A partially working version (at least it constructs the type when a value is passed) is
```
class Superclass
  setting :authorization, &Authorizer.method(:call)
end
```
but still the default value is not used.

I am sure I'm missing something, could you point me to the right direction?

**Comment by GustavoCaso** [comment]
@AMHOL I think it would be great to continue with this `feature`

**Comment by GustavoCaso** [comment]
This feature has been added in this commit 1caa28e3b405db806aaf1dc09748e1213ec9bd08
