### ISSUE TITLE
Callback "after configure"

### ISSUE THREAD

**Issue by kwando** [dry-rb/dry-configurable#39]
I'm just throwing this idea out there, but it would be nice to have a "before configuration changed" callback triggered when configuration is about to be changed. 
This would give us a hook to validate the configuration before accepting it.

**Comment by GustavoCaso** [comment]
When would you like to change the configuration, could you provide an example ?

**Comment by GustavoCaso** [comment]
I'm closing this one since there is no more activity on the subject.
