### ISSUE TITLE
Lazy loaded default parameters

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-configurable#4]
Will there be a support for lazy loaded default options values? I have some settings that if not set, should be set from proc during runtime (with first invocation)

**Comment by mensfeld** [comment]
Did a temporary patch:

```ruby
# Patch that will allow to use proc based lazy evaluated settings with Dry Configurable
class Dry::Configurable::Config
  # @param [Array] All arguments that a Struct accepts
  def initialize(*args)
    super
    setup_dynamics
  end

  private

  # Method that sets up all the proc based lazy evaluated dynamic config values
  def setup_dynamics
    self.to_h.each do |key, value|
      next unless value.is_a?(Proc)

      rebuild(key)
    end
  end

  # Method that rebuilds a given accessor, so when it consists a proc value, it will
  # evaluate it upon return
  # @param method_name [Symbol] name of an accessor that we want to rebuild
  def rebuild(method_name)
    metaclass = class << self; self; end

    metaclass.send(:define_method, method_name) do
      super().is_a?(Proc) ? super().call : super()
    end
  end
end

```

**Comment by AMHOL** [comment]
@mensfeld sorry I missed this, I think this is out of scope of the core lib, perhaps we could add config to set a custom `Config` class, not sure whether that's a good idea yet tho.

**Comment by timriley** [comment]
@AMHOL FYI, I've kind of wanted this at times, especially when trying to set up default settings that depend on values of other settings. In the end I think I override `.configure` to achieve it:

```
def self.configure(&block)
  super
  config.some_other_setting = stuff_using(config.another_setting)
end
```

**Comment by mensfeld** [comment]
@AMHOL  no problem :) it happens to me as well. I'm not sure about the method but I feel that there should be a way to do stuff like that (and what @timriley  needs as well)

**Comment by AMHOL** [comment]
Would something like this work for both of you?

```ruby
class App
  extend Dry::Configurable

  setting :db_adapter, 'postgres'
  setting :db_user, 'root'
  setting :db_password, ''
  setting :db_host, '127.0.0.1'
  setting :db_port, '127.0.0.1'
  setting :db_name, 'development'
  # This \/ \/
  setting :dsn do |config|
    "#{config.db_adapter}://#{config.db_user}:#{config.db_password}@#{config.db_host}:#{config.db_port}/#{config.db_name}"
  end
end
```

**Comment by mensfeld** [comment]
@AMHOL for me yes :) as long as #dns will be built on the first invokation :+1:

**Comment by AMHOL** [comment]
@timriley ?

**Comment by timriley** [comment]
I reckon something like that'd work, yeah :)

**Comment by AMHOL** [comment]
@timriley @mensfeld check out https://github.com/dry-rb/dry-configurable/pull/10

**Comment by AMHOL** [comment]
Been thinking more about this and I'm not sure it's a good idea, do you have any real-world examples of this @timriley @mensfeld ?

**Comment by mensfeld** [comment]
@AMHOL yup. Here you go: https://github.com/karafka/karafka/blob/master/lib/karafka/setup/config.rb#L42

**Comment by AMHOL** [comment]
Is that something that can/should be overridden?

**Comment by mensfeld** [comment]
@AMHOL  it is something that needs to be lazy loaded on the first evaluation. It cannot be specified during boot.

**Comment by timriley** [comment]
@AMHOL I think my use cases would all be covered by #9 if we built that instead.

**Comment by solnic** [comment]
I'm late to the party (I forgot to watch this project again after my "break from oss" in May...) - anyhow, I'm wondering if we really need this. It seems to me that it's more an issue of loading things in correct order so that when config is being loaded, things that it depends on will be loaded first. In general configuring things at run-time is a bad idea. Is it really not possible to initialize dependencies before your config, @mensfeld?

**Comment by mensfeld** [comment]
@solnic well I'm my particular case it isn't. I can't initialize list of Kafka servers until uses configures his part. One solution for me would be to use 2 configs - one for Karafka user and one internal, however Kafka servers can be also provided manually and this should overwrite the lazy loaded discovering. I don;t really need that feature to be merged as I already patched it ;) However I still think that it is a valid case.

**Comment by AMHOL** [comment]
@mensfeld @solnic @timriley going to close this as I agree with @solnic here and as you mentioned you already have a patch applied to fit your use-case.
