### ISSUE TITLE
Feature request — allow to easily reset configuration to original state

### ISSUE THREAD

**Issue by kigster** [dry-rb/dry-configurable#45]
First of all, I wanted to thank the core crew for the fantastic work. I am really enjoying using most of the `dry-rb` gems in my [most recent projects](https://github.com/kigster/arli).

However, particularly with RSpec, and since the gem sets the `<Module>.config` at the module level, I was unable to find an easy way to reset my config back its original state at the beginning of each test. I don't have the defaults specified everywhere, so some fields should become nil, and I couldn't find an easy way of doing that.

Any chance you can either suggest how I go about submitting a PR, or perhaps you can suggest an existing solution?

Thanks!

**Comment by saiqulhaq** [comment]
maybe through this one
https://github.com/dry-rb/dry-configurable/blob/1caa28e3b405db806aaf1dc09748e1213ec9bd08/lib/dry/configurable/test_interface.rb

**Comment by flash-gordon** [comment]
I believe https://github.com/dry-rb/dry-rb.org/pull/235 addresses the issue
