### ISSUE TITLE
Apply configuration from existing hash

### ISSUE THREAD

**Issue by saverio-kantox** [dry-rb/dry-configurable#46]
When you load configuration from, say, a YAML file, you already have a hash. It would be awesome to have a method that automatically recurs into the hash assigning configuration:
```
hash = YAML.load_file('config/database.yaml')
MyConfigurableClass.config.load_hash(hash)
```

**Comment by GustavoCaso** [comment]
Hi, @saverio-kantox sorry for the huge delay on this issue. Would you care to share a scenario where this could come in handy?

**Comment by dikond** [comment]
Hello :v: One use case would be to define default global configuration, but leave an option to rewrite configuration on individual basis. 

I'm building a gem for error normalization. It consists of several independent objects which depend on configuration. All of them hidden under facade with a single public API like

    ErrorNormalizer.normalize(input, **options)

If we gonna take a typical rails app, we can put some configuration in initializer, like that

    ErrorNormalizer.configure do |config|
      config.infer_type_from_rule_name = true
    end

Now behavior of ErrorNormalizer configured globally, but if in some particular place I want to turn off that setting, would be cool to just pass it like

    ErrorNormalizer.normalize(input, infer_type_from_rule_name: false)

It would be handy to build a new configuration object inside `normalize`, merge it with global settings defined in initializer and pass it down to other components.
