### ISSUE TITLE
[Bug] Preprocessor are not used for initial nil value

### ISSUE THREAD

**Issue by 0exp** [dry-rb/dry-configurable#51]
**(version 0.7.0)**
Preprocessor is not used for initial nil value.

Example:
- `any_key` - with initial nil value
- `another_key` - with explicit default value

```ruby
class A
  extend Dry::Configurable
  setting(:any_key) { |value| "empty value" }
  setting(:another_key, 25) { |value| "#{value} number" }
end

A.config.any_key # => nil # [BUG] Initial `nil` value, not preprocessed.
A.config.any_key # => nil # still not using a pre-processor
A.config.any_key = 25
A.config.any_key # => "empty value"
A.config.any_key = nil 
A.config.any_key # => "empty_value" (each next invocations uses a pre-processor after redifinition)
A.config.another_key # => "25 number"
```

Bug?

**Comment by ilnurnasyrov** [comment]
it looks like it is correct behavior for 0.7.0 according to [documentation](http://dry-rb.org/gems/dry-configurable/) :

```ruby
  # Pass a block for nested configuration (works to any depth)
  setting :database do
    # Can pass a default value
    setting :dsn, 'sqlite:memory'
  end
  # Defaults to nil if no default value is given
  setting :adapter
  # Pre-process values
  setting(:path, 'test') { |value| Pathname(value) }
```

**Comment by 0exp** [comment]
@ilnurnasyrov  Explicit nil values are not preprocessed too (until you redefine it). 

```ruby
class A
  extend Dry::Configurable
  setting(:any_key, nil) { |value| "empty value" }
end

A.config.any_key # => nil
..etc...
```

In real projects `nil` value can be as default for some cases and i want to use this.

---

```
If we pass default value it will use preprocessor, if we don't pass default value explicitly it will use nested configuration.
```

This is confusing cuz manually defined nils in runtime uses pre-processor object (see my examples above). In this case dry-configurable should use keyword attributes to avoid this confusion.

**Comment by flash-gordon** [comment]
This is fixed in master, I added a spec ensuring that explicit `nil` value as default is passed to the processor.
