### ISSUE TITLE
Suggestion: remove the .ruby-version file ?

### ISSUE THREAD

**Issue by lerencao** [dry-rb/dry-configurable#6]
As the title says.

**Comment by AMHOL** [comment]
Could you expand on that please?

**Comment by lerencao** [comment]
Maybe someone wants to clone the gem and rake it with his 2.3.0 version, but with 2.0.0 not installed.
I know deleting it could be a quick solution, but from the beginning, I think it should not be there, and the file should be ignored in `.gitignore`

**Comment by AMHOL** [comment]
:+1: Thanks, I'll remove it and add to .gitignore when I next get a chance, PRs welcome too :smile:

**Comment by lerencao** [comment]
Then closed. btw, thanks for the dry gems.

**Comment by AMHOL** [comment]
Thanks for checking them out :smiley:
