### ISSUE TITLE
Reader option

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-configurable#8]
I've found myself doing that a lot:

``` ruby
class Foo
  extend Dry::Configurable

  setting :something

  def self.something
    config.something
  end
end
```

WDYT about this:

``` ruby
class Foo
  extend Dry::Configurable

  setting :something, reader: true
end
```

**Comment by artofhuman** [comment]
What behavior for reader should be for this example?
 ``` ruby
class Foo 
  extend Dry::Configurable
  
  setting :database, reader: true do
    setting :dsn, 'sqlite:memory'
  end
end

**Comment by AMHOL** [comment]
I'm not sure it would be necessary on nested settings as a reader on the root setting would make the child settings available as i.e. `database.dsn`

**Comment by AMHOL** [comment]
Not sure about this as it introduces different behaviour based on the level of nesting, plus you could just use Forwardable and delegators to do the same

**Comment by solnic** [comment]
@AMHOL wdym?

**Comment by timriley** [comment]
@AMHOL's probably talking about what happens with something like this, for example?

```ruby
setting :foo do
  setting :bar, reader: true
end
```

**Comment by solnic** [comment]
Nesting shouldn't be supported as it makes no sense :)

**Comment by AMHOL** [comment]
@solnic I'm not sure the option should be supported though, the way the library works it can't be implemented on the root level without also being implemented at the nested level, and I'm not sure whether a library for configuration should support an option to expand the interface of an object. With `Forwardable` I meant something like:

```ruby
class App
  extend Dry::Configurable

  class << self
    extend Forwardable
    def_delegator :config, :database
  end

  # Pass a block for nested configuration (works to any depth)
  setting :database do
    # Can pass a default value
    setting :dsn, 'sqlite:memory'
  end
  # Defaults to nil if no default value is given
  setting :adapter
end

App.database
=> #<struct dsn="sqlite:memory">
```

**Comment by GustavoCaso** [comment]
@AMHOL I think we can close this one
