### ISSUE TITLE
Accessing settings as strings via `#[]`

### ISSUE THREAD

**Issue by waiting-for-dev** [dry-rb/dry-configurable#82]
**Describe the bug**

Before the update to 0.11, a setting could be referenced via a string through `config.[]`. Now it must be a symbol, otherwise the setting is not found.

I'd like to know if it's desired behavior. If not, I can send a patch myself.

**To Reproduce**

```ruby
class A
  extend Dry::Configurable

  setting :foo, :bar
end

A.config[:foo]
# => :bar
A.config["foo"]
# => ArgumentError (+foo+ is not a setting name)
```

**Expected behavior**

```ruby
A.config["foo"]
# => :bar
```

**Your environment**

Affects two gems I maintain:

https://github.com/waiting-for-dev/warden-jwt_auth/issues/21
https://github.com/waiting-for-dev/devise-jwt/issues/159

**Comment by solnic** [comment]
> I can send a patch myself.

Please do. My intention was to maintain public API behavior.
