### ISSUE TITLE
Option parser

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-configurable#9]
Sometimes you may want to pre-process a value, ie:

``` ruby
class Foo
  extend Dry::Configurable

  setting :path { |value| Pathname(value) }
end
```

**Comment by timriley** [comment]
This would be handy. In the past I've had to override it by doing something like this:

```ruby
class Foo
  extend Dry::Configurable
  setting :path

  def self.path
    Pathname(config.path)
  end
end
```

And then remembering to use that reader everywhere rather than the config value directly.

**Comment by AMHOL** [comment]
@solnic @timriley this could be covered by https://github.com/dry-rb/dry-configurable/pull/10

```ruby
class Foo
  extend Dry::Configurable

  setting :path
  setting(:pathname) { |config| Pathname(config.path) }
end

Foo.configure do |config|
  config.path = 'test'
end

Foo.config.pathname
=> #<Pathname:test>
```

**Comment by solnic** [comment]
Not sure if I follow, this seems like two different things

**Comment by timriley** [comment]
Yeah, the fact that we end up with 2 configs in that example, when we really only wanted one that we could modify when it's set, shows that #10 (if we did decided to incorporate it) doesn't achieve the feature described here all that well?

**Comment by AMHOL** [comment]
Yeah I was thinking about this the other night and came to the same conclusion

**Comment by AMHOL** [comment]
@solnic @timriley WDYT about an interface like:

```ruby
class Foo
  extend Dry::Configurable

  setting :path, processor: ->(value) { Pathname(value) }
end
```

**Comment by AMHOL** [comment]
See: https://github.com/dry-rb/dry-configurable/pull/11
