### ISSUE TITLE
Does not work from within a trap context

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-configurable#93]
**Describe the bug**

dry-configurable does not work from a trap context

**To Reproduce**

Run the following script and press CTRL+C to stop it:

```ruby
require 'dry/configurable'

class App
  extend Dry::Configurable

  setting :adapter, 'lol'
end

def trap_signal
  trap("INT") do
    p App.config.adapter
    exit
  end
end

trap_signal

sleep
```

Output:

```ruby
^CTraceback (most recent call last):
  14: from run.rb:18:in `<main>'
  13: from run.rb:18:in `sleep'
  12: from run.rb:11:in `block in trap_signal'
  11: from dry-configurable-0.11.5/lib/dry/configurable/class_methods.rb:72:in `config'
  10: from dry-configurable-0.11.5/lib/dry/configurable/class_methods.rb:72:in `new'
   9: from dry-configurable-0.11.5/lib/dry/configurable/config.rb:26:in `initialize'
   8: from dry-configurable-0.11.5/lib/dry/configurable/config.rb:26:in `dup'
   7: from dry-configurable-0.11.5/lib/dry/configurable/config.rb:26:in `initialize_dup'
   6: from dry-configurable-0.11.5/lib/dry/configurable/settings.rb:61:in `initialize_copy'
   5: from dry-configurable-0.11.5/lib/dry/configurable/settings.rb:66:in `initialize_elements'
   4: from dry-configurable-0.11.5/lib/dry/configurable/settings.rb:66:in `each_with_object'
   3: from dry-configurable-0.11.5/lib/dry/configurable/settings.rb:66:in `each'
   2: from dry-configurable-0.11.5/lib/dry/configurable/settings.rb:67:in `block in initialize_elements'
   1: from concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:18:in `[]='
concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:18:in `synchronize': can't be called from trap context (ThreadError)
```

**Expected behavior**

The system should print the config value and exit

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.6.5 and 2.7.0
- OS: Ubuntu

**Bypass**

Spawning a thread to bypass the trap context works but it's rather clumsy:

```ruby
p Thread.new { App.config.adapter }.join.value
```

**Comment by solnic** [comment]
Looks like concurrent map cannot be used in this context so I'm not sure if we can do anything about this, unless there's no need to use concurrent map there?

**Comment by mensfeld** [comment]
> there's no need to use concurrent map there?

Dunno. If dry-configurable should not be used from the trap context, it should be pointed out in the docs (and in a rather loud way). I don't see any non-implementation reason for it not to be usable tbh.

**Comment by flash-gordon** [comment]
I agree with @eregon, I don't think we can or should fix this

**Comment by mensfeld** [comment]
> Potentially this could be considered as MRI being too strict? Forbidding Mutex#synchronize in trap seems unfortunate, even though indeed there is a risk of deadlock since the main thread might already have the Mutex and it's not reentrant.

Well this is what I do ;) just wanted to set some things based on a config that in theory should just be readable without having to have mutex. Guess I was wrong.

Since I already have a bypass in place I will close this one, though I do think it would be good to include this case in the readme or the docs.
