### ISSUE TITLE
Values are being memoized between config instances

### ISSUE THREAD

**Issue by madejejej** [dry-rb/dry-configurable#96]
**Describe the bug**

This is a regression between versions 0.11.5 and 0.11.6. When you instantiate multiple instances of a class that include `Dry::Configurable`, the default values specified in the `setting` block are memoized between the instances. 

I'm including a simplified reproduction script based on an issue with https://github.com/karafka/waterdrop/.

You can instantiate multiple WaterDrop consumers, each with different settings. WaterDrop has a default `monitor` (based on `dry-monitor`), which is instantiated by `dry-configurable`. 

We subscribe to each consumer's monitor so that we can publish instrumentation metrics:

```ruby
listener = KafkaStatsdListener.new
publisher.monitor.subscribe(listener)
publisher2.monitor.subscribe(listener)
```

This works fine with 0.11.5, but with 0.11.6 the messages from the monitor are duplicated.

**To Reproduce**

```ruby
require 'dry-configurable'
require 'dry/configurable/version'

MyMonitor = Class.new

class Producer
  include Dry::Configurable

  setting(:monitor, false) { |monitor| monitor || MyMonitor.new }
end

producer1 = Producer.new
producer2 = Producer.new

puts "dry-configurable version: #{Dry::Configurable::VERSION}"
puts producer1.config.monitor.object_id == producer2.config.monitor.object_id
```

Output:
```
dry-configurable version: 0.11.6
true
```

**Expected behavior**

```
dry-configurable version: 0.11.5
false
```

**Comment by esparta** [comment]
I just checked the diff and everything goes down to #95 specifically the line 64 on `configurable/setting.rb`:

https://github.com/dry-rb/dry-configurable/blob/9e08e70cd1069b0d5dc939dc6ed21634ec0b5534/lib/dry/configurable/setting.rb#L57-L65

Let me see if would be possible to maintain both behaviors.

**Comment by esparta** [comment]
just added a PR to fix this issue, it still need to check all other dry-* gems who depends on this gem

**Comment by timriley** [comment]
@madejejej This is fixed in master now; I'll cut a new patch release next week :)

**Comment by timriley** [comment]
@madejejej  Would you mind giving the master branch a go to make sure it fixes your specific problem?

**Comment by madejejej** [comment]
@timriley thanks for looking into this! The fix on the master branch works.
